scrape_configs:
  - job_name: 'ping'
    metrics_path: /probe
    params:
      module: ["icmp"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.1.49:9115
    static_configs:
      - targets:
          - "192.168.1.44"
          - "192.168.1.46"